### ISSUE TITLE
启动报错Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by mxian** [uniquetruth/remote-debug-agent#20]
我直接命令行里面执行

D:\workspace\gitlab\XXXXXX>java -javaagent:D:\workspace\gitlab\XXXXXX\remote-debug-agent.jar=includes=com.XXXXXX.prd,apiport=9099 -jar XXXXXX.jar

AgentEntrance.premain() was called. +++ agentArgs:includes=com.fofund.prd,apiport=9099
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: RealAgent reflect exception.
        at com.github.rdagent.AgentEntrance.doPremain(AgentEntrance.java:70)
        at com.github.rdagent.AgentEntrance.premain(AgentEntrance.java:22)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.github.rdagent.AgentEntrance.doPremain(AgentEntrance.java:68)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
        at com.github.rdagent.transformer.AsmTransformer.<init>(AsmTransformer.java:29)
        at com.github.rdagent.RealAgent.doAgentEnter(RealAgent.java:37)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.github.rdagent.loader.Agent3rdPartyClassloader.loadClass(Agent3rdPartyClassloader.java:273)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 14 more
FATAL ERROR in native method: processing of -javaagent failed

**Comment by mxian** [comment]
好吧，是我少复制了jar
